version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/examples/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/examples/nextjs-app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/environments/host"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/environments/service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/examples/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/examples/nextjs-app"
    schedule:
      interval: "weekly"
